POST localhost:8080/auth/public/registration
Content-Type: application/json

{
  "name": "Suxrob",
  "email": "suxrobbek997@gmail.com",
  "password": "123"
}
###
POST localhost:8080/auth/public/registration
Content-Type: application/json

{
  "name": "Vali",
  "email": "",
  "password": "123"
}

###
POST localhost:8080/auth/public/login
Content-Type: application/json

{
  "email": "world997dev@mail.ru",
  "password": "123"
}
###
POST localhost:8080/auth/public/login
Content-Type: application/json

{
  "email": "suxrobbek997@gmail.com",
  "password": "123"
}
###
POST localhost:8080/auth/public/login
Content-Type: application/json

{
  "email": "omonxonovsaidkarim1998@gmail.com",
  "password": "123"
}

###
GET http://localhost:8080/auth/public/email/verification/18

###
GET http://localhost:8080/auth/public/resend/email/eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc5NDUwODAsImV4cCI6MTY1ODE2MTA4MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxN30.EO6StcseJpeH0nAkNeAVAs4tof1F0Y5oifm5nH1adiE