GET localhost:8080/email/adm/list?size=3&page=0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc5NDgwNjcsImV4cCI6MTY1ODE2NDA2NywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.jsXX5t7cVsaif1j7FiuwHd2AKza8v2xsommAHIuN2SY


#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc5NDc5NjksImV4cCI6MTY1ODE2Mzk2OSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxN30.P2GuHzlYTASLHNYKzAHyYuDOZiVQQrQ8Mb_GTmkcbVA
