POST http://localhost:8080/video/public/create
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="123.mp4"

< C:\Users\SUKHROB\Desktop\123.mp4

###
GET http://localhost:8080/attach/public/open/524551d1-ca59-4967-9df3-05abe4d9ea1c

###
GET localhost:8080/attach/public/open/524551d1-ca59-4967-9df3-05abe4d9ea1c